development:
  adapter: sqlite3
  database: database.db

test:
  adapter: sqlite3
  database: database.db

production:
  adapter: postgresql
  database: silhouettes
  username: heroku
  password: sublime_connection9
  host: localhost
