development:
  adapter: sqlite3
  database: database.db

test:
  adapter: sqlite3
  database: database.db

production:
  adapter: postgresql
  database: silhouette
  username: Mackenzie
  password: 4d4mpwn530A
  host: localhost
